name = "GoogleTakeOuter"
uuid = "6098eff3-57f8-4dc0-be6c-60df947aebac"
authors = ["Matthieu Tisserand <matthieu.tisserand@polytechnique.org> and contributors"]
version = "1.0.0-DEV"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
FileIO = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
